import{S as w,a as b,i as n}from"./assets/vendor-MjawMu3A.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const f=document.querySelector(".gallery"),m=document.querySelector(".load-more"),y=document.querySelector(".loader"),v=new w(".gallery a",{captionsData:"alt",captionDelay:250});function S(){f.innerHTML=""}function p(o){const t=o.map(a=>`
        <li class="gallery-item">
            <a href="${a.largeImageURL}">
                <img src="${a.webformatURL}" alt="${a.tags}" />
            </a>
            <ul class="info">
                <li><span>Likes:</span> ${a.likes}</li>
                <li><span>Views:</span> ${a.views}</li>
                <li><span>Comments:</span> ${a.comments}</li>
                <li><span>Downloads:</span> ${a.downloads}</li>
            </ul>
        </li>`).join("");f.insertAdjacentHTML("beforeend",t),v.refresh()}function h(){y.classList.add("is-visible")}function c(){y.classList.remove("is-visible")}function q(){m.classList.add("visible")}function g(){m.classList.remove("visible")}const B="https://pixabay.com/api/",M="8510354-a536a728c4badadcbc80336ea";async function L(o,t){return(await b.get(B,{params:{key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const $=document.querySelector(".form"),P=document.querySelector(".load-more");let i="",s=1,u=0;$.addEventListener("submit",O);P.addEventListener("click",x);async function O(o){if(o.preventDefault(),i=o.target.elements["search-text"].value.trim(),!i){n.error({message:"Please enter a search query!"});return}s=1,S(),g(),h();try{const t=await L(i,s);if(u=t.totalHits,t.hits.length===0){c(),n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}p(t.hits),s*15<u&&q()}catch{n.error({message:"Something went wrong..."})}finally{c()}}async function x(){s+=1,h();try{const o=await L(i,s);p(o.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),s*15>=u&&(g(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Something went wrong..."})}finally{c()}}
//# sourceMappingURL=index.js.map
