import{S as w,a as b,i}from"./assets/vendor-MjawMu3A.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const d=document.querySelector(".gallery"),f=document.querySelector(".load-more"),m=document.querySelector(".loader"),v=new w(".gallery a",{captionsData:"alt",captionDelay:250});function S(){d.innerHTML=""}function y(o){const t=o.map(a=>`
        <li class="gallery-item">
            <a href="${a.largeImageURL}">
                <img src="${a.webformatURL}" alt="${a.tags}" />
            </a>
            <ul class="info">
                <li><span>Likes:</span> ${a.likes}</li>
                <li><span>Views:</span> ${a.views}</li>
                <li><span>Comments:</span> ${a.comments}</li>
                <li><span>Downloads:</span> ${a.downloads}</li>
            </ul>
        </li>`).join("");d.insertAdjacentHTML("beforeend",t),v.refresh()}function p(){m.classList.add("is-visible")}function h(){m.classList.remove("is-visible")}function q(){f.classList.add("visible")}function g(){f.classList.remove("visible")}const B="https://pixabay.com/api/",M="8510354-a536a728c4badadcbc80336ea";async function L(o,t){return(await b.get(B,{params:{key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const $=document.querySelector(".form"),O=document.querySelector(".load-more");let n="",s=1,c=0;$.addEventListener("submit",P);O.addEventListener("click",x);async function P(o){if(o.preventDefault(),n=o.target.elements["search-text"].value.trim(),!!n){s=1,S(),g(),p();try{const t=await L(n,s);if(c=t.totalHits,t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t.hits),s*15<c&&q()}catch{i.error({message:"Something went wrong..."})}finally{h()}}}async function x(){s+=1,p();try{const o=await L(n,s);y(o.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),s*15>=c&&(g(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({message:"Something went wrong..."})}finally{h()}}
//# sourceMappingURL=index.js.map
